server:
  port: 8081

spring:
  application:
    name: auth-service

management:
  tracing:
    sampling:
      probability: 0.0
  zipkin:
    tracing:
      endpoint: http://localhost:9411/api/v2/spans
  endpoints:
    web:
      exposure:
        include: info,health,prometheus

logging:
  level:
    org:
      springframework:
        ws: INFO
        security: INFO
    org.hibernate.SQL: DEBUG
    org.hibernate.orm.jdbc.bind: TRACE

maxFailedLoginAttempt: 5

oauth:
  properties:
    default-access-token-timeout: 3600
    default-refresh-token-timeout: 86400
